import { Shield } from 'lucide-react';

export default function PrivacyPage() {
  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="text-center py-4">
        <div className="flex items-center justify-center gap-3 mb-2">
          <Shield className="w-8 h-8 text-lucky-success" />
          <h1 className="text-3xl font-bold text-lucky-text dark:text-lucky-dark-text">
            Privacy Policy
          </h1>
        </div>
        <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted">
          Last updated: January 2026
        </p>
      </div>

      {/* Content */}
      <div className="bg-lucky-surface dark:bg-lucky-dark-surface rounded-xl p-6 md:p-8 border border-lucky-border dark:border-lucky-dark-border space-y-8">
        
        {/* Overview */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            Overview
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed">
            At LuckyLens, we take your privacy seriously. This Privacy Policy explains how we handle 
            your information when you use our application. We believe in a minimal data approach: 
            we collect as little information as possible and store everything locally on your device. 
            This Privacy Policy is designed to be transparent about our practices so you can make 
            informed decisions about using our App.
          </p>
        </section>

        {/* Information We Collect */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            Information We Collect
          </h2>
          <div className="p-4 bg-green-50 dark:bg-green-900/20 rounded-lg border border-green-200 dark:border-green-800">
            <p className="text-green-800 dark:text-green-200 font-medium">
              None.
            </p>
          </div>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mt-3">
            LuckyLens does not collect, transmit, or store any personal information on external servers. 
            We do not require you to create an account, provide an email address, or share any personally 
            identifiable information to use the App. All data generated by your use of the App remains 
            exclusively on your device.
          </p>
        </section>

        {/* Local Data Storage */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            Local Data Storage
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mb-3">
            All app data is stored locally on your device using browser storage technologies:
          </p>
          <ul className="list-disc list-inside space-y-2 text-lucky-text-muted dark:text-lucky-dark-text-muted ml-4">
            <li>
              <strong>IndexedDB:</strong> Used to store your saved number sets, historical draw results, 
              and app settings. This is a browser-based database that keeps data on your device.
            </li>
            <li>
              <strong>localStorage:</strong> Used for lightweight settings like theme preferences and 
              last sync timestamps. This is also stored locally in your browser.
            </li>
          </ul>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mt-3">
            This data never leaves your device. We cannot access it, nor can any third parties. 
            You have full control over this data and can delete it at any time through the App&apos;s 
            Settings page or by clearing your browser&apos;s storage.
          </p>
        </section>

        {/* Third-Party Services */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            Third-Party Services
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mb-3">
            The App may fetch publicly available lottery results from external APIs. These requests:
          </p>
          <ul className="list-disc list-inside space-y-2 text-lucky-text-muted dark:text-lucky-dark-text-muted ml-4">
            <li>Do not include any personal information</li>
            <li>Are made anonymously from your device</li>
            <li>Only retrieve publicly available winning numbers</li>
          </ul>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mt-3">
            <strong>We do not use:</strong>
          </p>
          <ul className="list-disc list-inside space-y-2 text-lucky-text-muted dark:text-lucky-dark-text-muted ml-4">
            <li>Analytics services (Google Analytics, Mixpanel, etc.)</li>
            <li>Advertising networks or trackers</li>
            <li>Social media SDKs or sharing libraries that track users</li>
            <li>Crash reporting services that collect device information</li>
          </ul>
        </section>

        {/* Cookies */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            Cookies
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed">
            LuckyLens does not use cookies. We use localStorage and IndexedDB for storing app data 
            and preferences, which are browser storage mechanisms that differ from traditional cookies. 
            These storage methods do not transmit data to servers and remain entirely on your device.
          </p>
        </section>

        {/* Children's Privacy */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            Children&apos;s Privacy
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed">
            This App is not directed at children under the age of 18. Lottery-related content is 
            intended for adults only. We do not knowingly collect any information from children under 18. 
            If you are a parent or guardian and believe your child has used the App, please contact us 
            so we can address the situation. By using this App, you represent that you are at least 
            18 years old or have reached the age of majority in your jurisdiction.
          </p>
        </section>

        {/* Data Deletion */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            Data Deletion
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mb-3">
            You can delete all locally stored data at any time:
          </p>
          <ul className="list-disc list-inside space-y-2 text-lucky-text-muted dark:text-lucky-dark-text-muted ml-4">
            <li>
              <strong>Through the App:</strong> Go to Settings → Data Management to clear saved 
              numbers or synced results individually.
            </li>
            <li>
              <strong>Browser Settings:</strong> Clear site data/storage for luckylens.app in your 
              browser settings to remove all data at once.
            </li>
          </ul>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mt-3">
            Since all data is stored locally on your device, deleting it from your browser is 
            equivalent to deleting it from our systems. We have no backup or remote copy of your data.
          </p>
        </section>

        {/* Changes to This Policy */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            Changes to This Policy
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed">
            We may update this Privacy Policy from time to time. Any changes will be posted within 
            the App and the &quot;Last updated&quot; date at the top of this page will be revised. We encourage 
            you to review this Privacy Policy periodically to stay informed about how we protect your 
            information. Your continued use of the App after any changes constitutes acceptance of 
            the updated Privacy Policy.
          </p>
        </section>

        {/* Contact Us */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            Contact Us
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed">
            If you have any questions, concerns, or requests regarding this Privacy Policy or our 
            privacy practices, please contact us at:
          </p>
          <p className="mt-2">
            <a 
              href="mailto:contact@luckylens.app" 
              className="text-lucky-primary hover:underline"
            >
              contact@luckylens.app
            </a>
          </p>
        </section>

      </div>

      {/* Footer Note */}
      <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-xl border border-blue-200 dark:border-blue-800">
        <p className="text-sm text-blue-800 dark:text-blue-200 text-center">
          <strong>Note:</strong> This privacy policy is a template. Consult legal counsel before publishing to app stores.
        </p>
      </div>
    </div>
  );
}
