import { FileText } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="text-center py-4">
        <div className="flex items-center justify-center gap-3 mb-2">
          <FileText className="w-8 h-8 text-lucky-primary" />
          <h1 className="text-3xl font-bold text-lucky-text dark:text-lucky-dark-text">
            Terms of Service
          </h1>
        </div>
        <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted">
          Last updated: January 2026
        </p>
      </div>

      {/* Content */}
      <div className="bg-lucky-surface dark:bg-lucky-dark-surface rounded-xl p-6 md:p-8 border border-lucky-border dark:border-lucky-dark-border space-y-8">
        
        {/* Section 1 */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            1. Acceptance of Terms
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed">
            By downloading, installing, or using LuckyLens (&quot;the App&quot;), you agree to be bound by these 
            Terms of Service. If you do not agree to these terms, please do not use the App. These terms 
            constitute a legally binding agreement between you and LuckyLens regarding your use of the App.
          </p>
        </section>

        {/* Section 2 */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            2. Description of Service
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mb-3">
            LuckyLens is a free entertainment application designed to generate random and trend-based 
            lottery number combinations. The App provides the following services:
          </p>
          <ul className="list-disc list-inside space-y-2 text-lucky-text-muted dark:text-lucky-dark-text-muted ml-4">
            <li>Random number generation for various lottery games</li>
            <li>Trend analysis based on publicly available historical draw data</li>
            <li>Local storage of generated numbers and user preferences</li>
            <li>Access to historical winning numbers for educational purposes</li>
          </ul>
          <div className="mt-4 p-4 bg-amber-50 dark:bg-amber-900/20 rounded-lg border border-amber-200 dark:border-amber-800">
            <p className="text-sm text-amber-800 dark:text-amber-200">
              <strong>Important:</strong> LuckyLens is strictly for entertainment purposes only. 
              The App does not sell lottery tickets, predict winning numbers, or guarantee any outcomes. 
              All number generation is random or based on historical frequency analysis, which has 
              no predictive value for future draws.
            </p>
          </div>
        </section>

        {/* Section 3 */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            3. No Guarantees or Warranties
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mb-3">
            LuckyLens makes no representations or warranties of any kind, express or implied, about:
          </p>
          <ul className="list-disc list-inside space-y-2 text-lucky-text-muted dark:text-lucky-dark-text-muted ml-4">
            <li>The completeness, accuracy, reliability, or availability of the App or its content</li>
            <li>The likelihood of winning any lottery using numbers generated by the App</li>
            <li>The accuracy of historical data or trend analysis</li>
            <li>The uninterrupted or error-free operation of the App</li>
          </ul>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mt-3">
            Lottery numbers are drawn randomly, and past results have no bearing on future outcomes. 
            Any numbers generated by this App have exactly the same probability of winning as any 
            other number combination. Using trend analysis or frequency data does not increase your 
            chances of winning.
          </p>
        </section>

        {/* Section 4 */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            4. User Responsibilities
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mb-3">
            By using LuckyLens, you agree to:
          </p>
          <ul className="list-disc list-inside space-y-2 text-lucky-text-muted dark:text-lucky-dark-text-muted ml-4">
            <li>Comply with all applicable local, state, and federal laws regarding lottery participation</li>
            <li>Ensure you are of legal age to participate in lottery games in your jurisdiction</li>
            <li>Play responsibly and within your means</li>
            <li>Not use the App for any illegal or unauthorized purpose</li>
            <li>Not attempt to reverse engineer, decompile, or hack the App</li>
            <li>Not use the App to harass, abuse, or harm others</li>
          </ul>
        </section>

        {/* Section 5 */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            5. Intellectual Property
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed">
            All content included in the App, including but not limited to text, graphics, logos, 
            icons, images, audio clips, digital downloads, data compilations, and software, is the 
            property of LuckyLens or its content suppliers and is protected by international copyright 
            laws. The compilation of all content in the App is the exclusive property of LuckyLens 
            and is protected by international copyright laws. All software used in the App is the 
            property of LuckyLens or its software suppliers and is protected by international copyright 
            laws.
          </p>
        </section>

        {/* Section 6 */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            6. Data Storage
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed">
            LuckyLens stores all user data locally on your device using browser storage technologies 
            (IndexedDB and localStorage). We do not collect, transmit, or store any personal information 
            on external servers. Your generated numbers, settings, and cached lottery results remain 
            solely on your device. You can delete this data at any time through the Settings page or 
            by clearing your browser data.
          </p>
        </section>

        {/* Section 7 */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            7. Limitation of Liability
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed">
            To the fullest extent permitted by applicable law, LuckyLens shall not be liable for any 
            indirect, incidental, special, consequential, or punitive damages, including but not limited 
            to loss of profits, data, use, goodwill, or other intangible losses, resulting from:
          </p>
          <ul className="list-disc list-inside space-y-2 text-lucky-text-muted dark:text-lucky-dark-text-muted ml-4 mt-3">
            <li>Your use or inability to use the App</li>
            <li>Any lottery losses incurred while using numbers generated by the App</li>
            <li>Any unauthorized access to or use of your local data</li>
            <li>Any errors, mistakes, or inaccuracies in the App&apos;s content</li>
            <li>Any interruption or cessation of transmission to or from the App</li>
          </ul>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed mt-3">
            By using this App, you acknowledge and agree that you are solely responsible for any 
            lottery tickets you purchase and any losses you may incur. LuckyLens is not responsible 
            for any gambling losses or decisions made based on information provided by the App.
          </p>
        </section>

        {/* Section 8 */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            8. Modifications to Terms
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed">
            LuckyLens reserves the right to modify these Terms of Service at any time. Changes will 
            be effective immediately upon posting the updated terms within the App. Your continued 
            use of the App after any changes constitutes acceptance of the new terms. We encourage 
            you to review these terms periodically for any updates.
          </p>
        </section>

        {/* Section 9 */}
        <section>
          <h2 className="text-xl font-semibold text-lucky-text dark:text-lucky-dark-text mb-3">
            9. Contact Information
          </h2>
          <p className="text-lucky-text-muted dark:text-lucky-dark-text-muted leading-relaxed">
            If you have any questions about these Terms of Service, please contact us at:
          </p>
          <p className="mt-2">
            <a 
              href="mailto:contact@luckylens.app" 
              className="text-lucky-primary hover:underline"
            >
              contact@luckylens.app
            </a>
          </p>
        </section>

      </div>

      {/* Footer Note */}
      <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-xl border border-blue-200 dark:border-blue-800">
        <p className="text-sm text-blue-800 dark:text-blue-200 text-center">
          <strong>Note:</strong> These terms are a template. Consult legal counsel before publishing to app stores.
        </p>
      </div>
    </div>
  );
}
